### ISSUE TITLE
Provide opt-out of css version of klaro

### ISSUE THREAD

**Issue by tillschweneker** [websedit/we_cookie_consent#12]
There is a klaro-no-css.js JS file available, which is useful for people who want to style the consent on their own.

Please include the no-css version in the extension as well and provide a setting to use this file.

https://github.com/kiprotect/klaro/blob/master/dist/klaro-no-css.js

**Comment by steinbinder** [comment]
There is ja new Option "No style" in the Style Prefix TypoScript constants. This loads klaro-no-css.js. Please give it a try. Thank you for the suggestion.

**Comment by mrleblanc101** [comment]
I see no documentation about this is the PDF.
How do I disable the CSS and load my custom CSS.
