### ISSUE TITLE
Description of cookie cannot contain special characters like quotes

### ISSUE THREAD

**Issue by cwiesenekker** [websedit/we_cookie_consent#14]
When a service/provider description containers special characters the app is not pushed to the cookie popup. Javascript breaks on: 

description: '<f:format.stripTags>{service.description}</f:format.stripTags>' in /Resources/Private/Partials/Klaro/App.html

Attached is a patch proposal to fix this. To the best of my knowledge such a viewhelper does not exist. Because the description is used in diffrent views maby its best to fix the formatting on repo level. Just always return html encoded content so you know how to parse it in the app. 

Patchfile attached

[wecookieconsent.diff.txt](https://github.com/websedit/we_cookie_consent/files/6198272/wecookieconsent.diff.txt)

**Comment by steinbinder** [comment]
Thank you for the Code Snippet. We have added it to the latest release.
