### ISSUE TITLE
Not compatible with Typo3 11

### ISSUE THREAD

**Issue by Jemus89** [websedit/we_cookie_consent#17]
Extension not compatible with Typo3 11. The solution would be to change line 90 in ConsentController.php in the renderAssetsForRequest method to check for instance of AbstractTemplateView instead of TemplateView

**Comment by pduersteler** [comment]
We just ran into this as well.. Are there any plans yet for getting a fix published in a new version? Can we lend a hand to help out?

**Comment by GregorWeb** [comment]
Hello everyone,
with the release of the version 3.0.1 we now support TYPO3 v10/v11.
We dropped the support for TYPO3 v7/v8 and v9.
