### ISSUE TITLE
Documentation: Missing hint to fill select categories as Klaro purposes

### ISSUE THREAD

**Issue by tpinne** [websedit/we_cookie_consent#2]
In both documentations (de + en) for version 1.3.x (others not checked) there is no mention at all, that the categories tab has to be used and something selected which configures the purpose property of Klaro. If no category is selected, no purpose is set in the Klaro app config and nothing will be displayed inside the modal to modify the settings.

It took me quite long to figure this out. Maybe add this to the documentation could help others too.

**Comment by steinbinder** [comment]
Unfortunately i made a small mistake in the changelog of version 1.3.3, which says we extended the docs with the categories feature. The documentation is currently under revision but not yet finished. We will provide it as soon as possible. I think one or two weeks.

**Comment by steinbinder** [comment]
The new documentation is now [online](https://consent.websedit.de/dokumentation). Chapter 4.2.3 gives a short explenation on how to use the sys_categories.

Thanks for the suggestion.
