### ISSUE TITLE
Google Consent Mode V2

### ISSUE THREAD

**Issue by ghwaldo** [websedit/we_cookie_consent#37]
Not a real Issue.

Is it possible to create a google consent mode v2 ?

I can not find info about that.

Seems that many users use services such as cookiebot etc.

Can anyone point me out ?

**Comment by romanliedtke** [comment]
The current version includes Google Consent Mode in simple and advanced mode. Please note that you need a tag template when using the Google Tag Manager in conjunction with Google Consent Mode.
([https://consent.websedit.de/dokumentation])

Further information can be found in the documentation:
([https://consent.websedit.de/dokumentation])

Feel free to give us feedback.
