### ISSUE TITLE
link to privacy property page is missing in EN

### ISSUE THREAD

**Issue by toccamonium-fe** [websedit/we_cookie_consent#4]
Hi,

awesome extension, thx. I just have a problem with the EN version of it as the [privacyPage] placeholder won't be resolved. In the German version it is and shows text and link to proper page. In the locallang.xlf the placeholder was not included, I put it there as I need the link in the banner.

<img width="643" alt="grafik" src="https://user-images.githubusercontent.com/55410878/92911641-5d0a1600-f429-11ea-830f-6c3fb5760f1a.png">

<img width="474" alt="grafik" src="https://user-images.githubusercontent.com/55410878/92911943-a0648480-f429-11ea-904d-98668a8645e0.png">

regards
Florian

**Comment by Jaykocha** [comment]
same here :/

**Comment by steinbinder** [comment]
Many thanks for the hints. I will look at it.

**Comment by Jaykocha** [comment]
Hey, just to clear it up a bit. I figured out it happens only on the starting page, f.e. 'abc.com' on subdomains like 'abc.com/sub' and all other subdomains, it was working fine. Maybe it helps you. Have a nice day!

**Comment by steinbinder** [comment]
I have released version 1.3.3 which hopefully fixes the bug. If you still have problems, I would like to ask you to test the new version. 
Until then I close this ticket. If the problem still occurs please reopen it. Thank you.
