### ISSUE TITLE
Undefined window.dataLayer 

### ISSUE THREAD

**Issue by msollmann** [websedit/we_cookie_consent#42]
Until the user has given his consent for GTM the window.dataLayer in ConsentController.js line 111 ("window.dataLayer.push(tempObj);") is undefined. When I uncomment "window.dataLayer.push(tempObj);" in line 71, it works.

**Comment by romanliedtke** [comment]
@msollmann Can you please explain your comment in more detail?
Is it an error or does the consent selection and the implementation of the code not work?

Explanation:
The function window.dataLayer.push(tempObj); in the script ConsentController.js line 111 is only called if it is a service that is implemented via the Google Tag Manager and therefore only if a Google Tag Manager service is active as a service in TYPO3. Services independent of GTM, such as Google Analytics, initialize the datalayer independently, e.g. in the file “google analytics.html”. If no datalayer is required, it is not initialized.

Translated with DeepL.com (free version)

**Comment by romanliedtke** [comment]
@msollmann we found the error and will fix it.

**Comment by romanliedtke** [comment]
> @msollmann we found the error and will fix it.

This is fixed in the new version.
