### ISSUE TITLE
Suggestion: Add trim around service description

### ISSUE THREAD

**Issue by tpinne** [websedit/we_cookie_consent#5]
A trim around the service description could be useful. If the description somehow starts with a linebreak after stripping the tags, the generated output is not valid json and therefore throws an error.

https://github.com/websedit/we_cookie_consent/blob/ed6cf270d5ca3d9b034019d9ab9d8f1a35b5f892/Resources/Private/Partials/Klaro/App.html#L12

**Comment by steinbinder** [comment]
Will have a look at it and add it in the next release.
