### ISSUE TITLE
consent for youtube - missing howto

### ISSUE THREAD

**Issue by mikeemike7** [websedit/we_cookie_consent#8]
Hello, is there a way to integrate YouTube videos into the consent manager, so that the consent can also be revoked if necessary?

**Comment by Karionis** [comment]
Hi, there's one not that comfortable possibility: You can create a cookie service of type “other”. There set a JavaScript callback function, which creates a cookie for the extension skvideo upon consent. The the extension plays or blocks YouTube videos depending on the existance of the cookie.

**Comment by stephangrass** [comment]
Hi, 
I think that an integration of the Klaro Contextual Consent would be a really great feature!
https://kiprotect.com/docs/klaro/tutorials/contextual_consent

Are there any plans for when this enhancement will take place?

**Comment by steinbinder** [comment]
We are currently working on this to implement. We plan to release a version 2.0.0 which includes klaros contextual consent feature by the end of march at the latest.

**Comment by stephangrass** [comment]
Hi,
the "Contextual Consent" function is not yet fully integrated in 2.0. Correct? What do you think when that will happen.

**Comment by peerlight** [comment]
any news on this in version 3.x?

**Comment by romanliedtke** [comment]
Contextual consent is working since version 3.x
