### ISSUE TITLE
deprecated use of ExtensionUtility::registerModule

### ISSUE THREAD

**Issue by SteffenKluetsch** [websedit/we_cookie_consent#9]
You still use the deprecated dot notation in the extension name for "VENDOR.EXT_NAME"

This changes in Typo3 11

`Error handler (BE): TYPO3 Deprecation Notice: Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin with argument $extensionName ("WE.WeCookieConsent") containing the vendor name ("WE") is deprecated and will stop working in TYPO3 11.0. in /html/production/typo3_src-10.4.10/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php line 63`

**Comment by steinbinder** [comment]
Thank's for the hint. I believe we still need this, as long as we want to support TYPO3 7.6. But I will check if this is true.

**Comment by steinbinder** [comment]
We have added a first support for TYPO3 11. But we will continue the development with new TYPO3 11 releases.
